// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::DateTime;
use chrono::offset::Utc;
#[derive(Queryable, Debug, Identifiable)]
#[primary_key(version)]
pub struct SqlxMigration {
    pub version: i64,
    pub description: String,
    pub installed_on: DateTime<Utc>,
    pub success: bool,
    pub checksum: Vec<u8>,
    pub execution_time: i64,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(annotation_type_id)]
pub struct AnnotationType {
    pub annotation_type_id: i32,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(command_annotation_id)]
pub struct CommandAnnotation {
    pub command_annotation_id: i64,
    pub command_id: i32,
    pub annotation_type_id: i32,
    pub annotation: Option<Jsonb>,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(command_id)]
pub struct Command {
    pub command_id: i64,
    pub named_command_id: i32,
    pub status: String,
    pub complete: bool,
    pub requested_at: DateTime<Utc>,
    pub initiator: Option<String>,
    pub source_system: Option<String>,
    pub reason: Option<String>,
    pub bypass_steps: Option<Json>,
    pub tags: Option<Jsonb>,
    pub context: Option<Jsonb>,
    pub identity_hash: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(dependent_system_object_map_id)]
pub struct DependentSystemObjectMap {
    pub dependent_system_object_map_id: i64,
    pub dependent_system_one_id: i32,
    pub dependent_system_two_id: i32,
    pub remote_id_one: String,
    pub remote_id_two: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(dependent_system_id)]
pub struct DependentSystem {
    pub dependent_system_id: i32,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(named_command_id)]
pub struct NamedCommand {
    pub named_command_id: i32,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct NamedCommandsNamedStep {
    pub id: i32,
    pub named_command_id: i32,
    pub named_step_id: i32,
    pub skippable: bool,
    pub default_retryable: bool,
    pub default_retry_limit: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(named_step_id)]
pub struct NamedStep {
    pub named_step_id: i32,
    pub dependent_system_id: i32,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(workflow_step_id)]
pub struct WorkflowStep {
    pub workflow_step_id: i64,
    pub command_id: i64,
    pub named_step_id: i32,
    pub depends_on_step_id: Option<i64>,
    pub status: String,
    pub retryable: bool,
    pub retry_limit: Option<i32>,
    pub in_process: bool,
    pub processed: bool,
    pub processed_at: Option<DateTime<Utc>>,
    pub attempts: Option<i32>,
    pub last_attempted_at: Option<DateTime<Utc>>,
    pub backoff_request_seconds: Option<i32>,
    pub inputs: Option<Jsonb>,
    pub results: Option<Jsonb>,
}

